### ISSUE TITLE
Use comma instead of apostrophe as thousands separator

### ISSUE THREAD

**Issue by danericryan** [KasparEtter/ef1p#3]
In section https://explained-from-first-principles.com/internet/#request-for-comments there is a reference to "9'000" that should be "9,000". Come to think of it, some English-speaking locations write "9.000". Feel free to close this as "won't fix" if the apostrophe was used to avoid style localization issues.

**Comment by KasparEtter** [comment]
Hi Dan, thank you for reporting this. I feel honored that you opened your first issue on GitHub in my project. 😊 (This is also the first issue in this repository, so congrats on that as well! 😉) The same problem also exists in the info box about [propagation delay](https://explained-from-first-principles.com/internet/#propagation-delay) ("300'000" instead of "300,000"). The apostrophe is the common way to indicate multiples of three digits in Switzerland. I'm aware that this is not common internationally but a comma is easily mistaken for a decimal mark. The best alternative would be to use a space but I don't really like that either. (See [here](https://ux.stackexchange.com/questions/23667/is-using-a-comma-as-a-number-separator-a-cultural-thing/23669) for a discussion about this.) I'm obviously biased but I truly think that the apostrophe is the best solution. Maybe I'll change my mind about this in the future. Until then, however, I use my artistic license to inspire others to adopt this style. 🤓 (Even though I will close this issue as "won't fix", I'm still glad that you opened it because now this decision and the reasoning behind it is publicly documented.)
